#!/usr/bin/env bash

if [[ $UID != 0 ]]; then
  echo "Please run this script with sudo:"
  echo "sudo $0 $*"
  exit 1
fi

getPackageManager() {
  UNCLEAN_OS=$(lsb_release -a | grep 'Distributor ID:' | tr '[:upper:]' '[:lower:]')
  if [[ "$UNCLEAN_OS" =~ "ubuntu" || "$UNCLEAN_OS" =~ "debian" ]]; then
    echo "apt-get update -y && apt dist-upgrade -y && apt install -y"
  elif [[ "$UNCLEAN_OS" =~ "arch" ]]; then
    echo "pacman -Syu"
  elif [[ "$UNCLEAN_OS" =~ "centos" ]]; then
    echo "yum install -y"
  elif [[ "$UNCLEAN_OS" =~ "fedora" ]]; then
    echo "dnf install -y"
  else
    # Assuming macOS
    echo "brew install"
  fi
}

LINUX_PACKAGES="arandr automake autorandr blueman build-essential default-jdk exfat-fuse gimp help2man i3 i3lock i3lock-fancy rofi scrot xss-lock"
AGNOSTIC_PACKAGES="emacs ffmpeg git neovim python3 tmux vim zsh"
PACKAGE_MANAGER_CMD=$(getPackageManager)

echo "Getting latest packages and installing base packages..."

eval "$PACKAGE_MANAGER_CMD $AGNOSTIC_PACKAGES"

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  eval "$PACKAGE_MANAGER_CMD $LINUX_PACKAGES"
fi

echo "Setting up basic dirs..."
mkdir -p ~/documents

./setup-links.sh

. ~/.zshrc

# Installing using scripts

# We might have already manually cloned dotfiles to get this script
if [[ ! -d "$HOME/developer/scripts" ]]; then
    git clone https://github.com/DarrienG/sillyscripts $HOME/developer/scripts
fi

echo "Installing alternative packages..."
echo "\tbrightness utils"
git clone https://github.com/haikarainen/light /tmp/light
cd /tmp/light
./autogen.sh && ./configure && make && sudo make install
cd

echo "Setting up git..."
git config --global user.email "darrienglasser@outlook.com"
git config --global user.name "DarrienG"

echo "Rocking a Thinkpad? This may be useful"
echo "GRUB_CMDLINE_LINUX_DEFAULT=\"quiet splash psmouse.synaptics_intertouch=0\""
echo "Related bug: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1722478\n\n"

echo "NOTE: You still need to:"
echo "Switch desktop environments"
echo "Add your ssh key to Github: https://github.com/settings/keys"
echo "Sign into Firefox"
echo "Download Slack and sign in!"
echo "Install Oh my Zsh:"
echo 'sh -c \"$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)\"'
echo "Run ./rust-setup.sh without root and go for it!"

echo "Setup complete!"
