#!/usr/bin/env bash

if [[ $UID != 0 ]]; then
    echo "Please run this script with sudo:"
    echo "sudo $0 $*"
    exit 1
fi

echo "Getting latest packages..."
sudo apt-get update -y && sudo apt-get dist-upgrade -y
echo "Cleaning up after upgrades..."
sudo apt-get autoclean -y && sudo apt-get autoremove -y

echo "Installing standard packages..."
sudo apt install build-essential exfat-fuse ffmpeg gimp git help2man kdenlive neovim zsh default-jdk taskwarrior scrot blueman xss-lock -y

echo "Installing nonstandard packages..."

echo "Installing Slack..."
sudo snap install slack --classic

echo "Installing i3..."
/usr/lib/apt/apt-helper download-file http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2018.01.30_all.deb keyring.deb SHA256:baa43dbbd7232ea2b5444cae238d53bebb9d34601cc000e82f11111b1889078a
dpkg -i ./keyring.deb
echo "deb http://debian.sur5r.net/i3/ $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=) universe" >> /etc/apt/sources.list.d/sur5r-i3.list
sudo apt update -y
sudo apt install i3 -y

echo "Setting up basic dirs..."
mkdir -p ~/Developer/dotfiles
mkdir -p ~/Documents

echo "Installing brightness utils..."
git clone https://github.com/haikarainen/light /tmp
cd /tmp/light
make && sudo make install
cd

echo "Setting up dotfiles..."
git clone https://github.com/DarrienG/dotfiles ~/Developer/dotfiles
mkdir -p ~/.config/i3
# i3
ln -s ~/Developer/dotfiles/i3 ~/.config/i3
ln -s ~/Developer/dotfiles/i3status ~/.config/i3status
# Vim
ln -s ~/Developer/dotfiles/.vim ~/.vim
ln -s ~/Developer/dotfiles/.vimrc ~/.vimrc
## Note these are "standard locations" in the case I move my dotfiles later
ln -s ~/.vim ~/.config/nvim
ln -s ~/.vimrc ~/.config/nvim/init.vim
# Zsh
ln -s ~/Developer/dotfiles/.zshrc ~/.zshrc
ln -s ~/Developer/dotfiles/.myshrc ~/.myshrc

echo "Setting up git..."
git config --global user.email "darrienglasser@outlook.com"
git config --global user.name "DarrienG"

clear
echo "NOTE: openjdk installed instead of Oracle JDK. If this is an issue run:"
echo "sudo add-apt-repository ppa:webupd8team/java"
echo "sudo apt update -y"
echo "sudo apt-get install oracle-java8-installer"\n\n

echo "Rocking a Thinkpad? This may be useful"
echo "https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1722478\n\n"

echo "NOTE: You still need to:"
echo "Switch desktop environments"
echo "Add your ssh key to Github: https://github.com/settings/keys"
echo "Sign into Firefox"
echo "Sign into Slack"
echo "Install Oh my Zsh:"
echo "sh -c \"$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)\""

echo "Setup complete!"

